version: '3'
services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD} # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 80:80
    command: /bin/bash -c "a2enmod rewrite && apache2-foreground"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
